meetupID: Jakarta-Kubernetes
meetupName: Jakarta Kubernetes
organizers:
- girikuncoro
- irvifa
- imrenagi
- iqbalfarabi
meetups:
  "20190110":
    title: "#1: Intro to Kubernetes and Knative"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/1VF_u0IYnvi0f-W2siKdFV8P1x6m6qzzblgYIAc5ZPq0
      speakers:
      - imrenagi
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=DZQOgIWN1pE
      slides: https://bit.ly/knative
      speakers:
      - pahleviauliya
      title: Exploring KNative
    - duration: 30m0s
      recording: ""
      slides: https://slides.com/qblfrb/kubernetesthe-ruby-way-71#
      speakers:
      - iqbalfarabi
      title: Kubernetes Fundamentals, The Beginning
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: gojek
      role: Venue
  "20190207":
    title: "#2: Kubernetes Architecture & Bukalapak Casestudy"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/170UG-e5XoEEpq6YUVOGDq6kPIwHOFBGWU0LppmWdc7o
      speakers:
      - imrenagi
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=eGUc4OPNMyU
      slides: https://docs.google.com/presentation/d/1-k5j5nORkBZ1gRIXicmIT9pdjhExlZdthGjyMBaV0pY
      speakers:
      - girikuncoro
      title: Kubernetes Architecture and Installation
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=gY6qUGp60pc
      slides: https://docs.google.com/presentation/d/1IXCX1XV-yY7qnwd0ZhEsGUDynpgm-TfIgpsfxBwRlY8
      speakers:
      - christoper.hans
      title: Kubernetes at Bukalapak, An SRE Perspective
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: biznet.gio
      role: Venue
  "20190312":
    title: "#3: Istio Night"
    presentations:
    - duration: 11m0s
      slides: https://slides.com/qblfrb/istio-night
      speakers:
      - iqbalfarabi
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=q-RWPjnJ2Y0&t=149
      slides: https://speakerdeck.com/meteatamel/stop-reinventing-the-wheel-with-istio
      speakers:
      - mete.atamel
      title: Stop Reinventing The Wheel with Istio
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=q-RWPjnJ2Y0&t=2974
      slides: https://docs.google.com/presentation/d/1qaREEr4kqTNDKyShAMcZbb6J7ETDPZdjUYo6aOTLC4Y
      speakers:
      - imrenagi
      title: Running Istio in TVLK Data Production
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: traveloka
      role: Venue
  "20190411":
    title: "#4: Kubernetes API Server and Service Discovery"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/1rDsxoPaHUW7VWFLypTXkllr5QjPKD0s8Zb9rmj6VToQ/edit?usp=sharing
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=IePXdP02eIo&t=5633
      slides: https://drive.google.com/file/d/1UJa4lfR4wfrey37Ud4XkH3ynTNf5Y6kq/view?usp=sharing
      speakers:
      - lukluk.santoso
      title: Service Discovery with Consul on Kubernetes
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=IePXdP02eIo&t=3700
      slides: https://docs.google.com/presentation/d/1zwiAjqGpyC4_lCUUFfklYdbSruQVvmKk3Jy6AAzXg-g/edit
      speakers:
      - irvifa
      title: Understanding Kubernetes API Server
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: cbncloud
      role: Venue
    - company: hpe
      role: Venue
  "20190511":
    title: "#5: Kubernetes Networking, CKA, and How to Contribute"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/1IQ4crMU4nHb2udkb14fYz_UFcRWWI-vLV5yAjWk402k
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/lJeKWFSy2nM
      slides: https://docs.google.com/presentation/d/1vcHsUL8f4PwYJaHKeQLkWG_s8np6Mj8C6IlwumcBS2w
      speakers:
      - arkan
      title: Networking Model and Services in Kubernetes
    - duration: 30m0s
      recording: https://youtu.be/AX-Rgs0SRrs
      slides: https://docs.google.com/presentation/d/1IJctTisfRQhTgkpyVUmgH3X6z9ozrXeJ8ta_6uSIt80
      speakers:
      - husni.alhamdani
      title: Journey and Tips on Passing CKA Certification
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=Zi2CzdQjx2Y
      slides: https://docs.google.com/presentation/d/1Bl0Msa_DUbwoY_d5_FAao9SzbYJKnvPRAVxmSMvSvzI
      speakers:
      - irvifa
      - girikuncoro
      title: How to Become Kubernetes Contributor
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: deeptech
      role: Venue
  "20190620":
    title: "#6: Service Mesh in AWS and Kube Deployment"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/1YxwY4yuUT1t0YuPbrulLIG1QUz80Wlv9PxJFxtvL0J0
      speakers:
      - girikuncoro
      - imrenagi
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/kBKuIN5kBYI
      slides: https://drive.google.com/open?id=1-OH3jkh-hse9jm4g6dUem0QSkZ4Dni22
      speakers:
      - indrajatiwidyatmoko
      title: Kubernetes Deployment, Rolling-Update, and Scaling
    - duration: 30m0s
      recording: https://youtu.be/xSEQb1FK0EY
      slides: https://drive.google.com/file/d/179J8jbbCQnPtIiZKMNc5R_QVzCILnQVa
      speakers:
      - donnie.prakoso
      title: Service Mesh with AWS
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: kitabisa
      role: Venue
  "20190711":
    title: "#7: Kubernetes Birthday Celebration"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/13jUXXzYlhRktwyJapjGeaPD-Bfz52dXyp3WP1RoU_O8
      speakers:
      - girikuncoro
      - imrenagi
      - irvifa
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      speakers:
      - luthfi.rachman
      title: Security Practices in Kubernetes
    - duration: 30m0s
      slides: https://docs.google.com/presentation/d/10KbPoYup4oKp-gCsXxMGJ7fNNfvWwXfYWHfTiBDZOHs
      speakers:
      - zufardhiyaulhaq
      title: "Kuryr Kubernetes: Interconnecting Kubernetes with Openstack"
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: google
      role: Venue
  "20190801":
    title: "#8: Kubernetes Monitoring and Stateful Basics"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/17s2c0NaeK_-GC6H0yuBG6mjdADGdVW-KuV1zAl-281o
      speakers:
      - girikuncoro
      - iqbalfarabi
      - irvifa
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=bYFwBqfGsx4
      slides: http://ela.st/aravind
      speakers:
      - aravind
      title: Docker and Kubernetes Monitoring with Elastic Stack
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=drBa7aBwKtA
      slides: https://docs.google.com/presentation/d/17UnrPmXNZS8EW3CbslDyC0iDb9O1cKjWV8K2r-ZMF1Q
      speakers:
      - kevin.tanzil
      title: Basic of Stateful and Storage in Kubernetes
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: linkaja
      role: Venue
    - company: elastic
      role: Venue
  "20190904":
    title: "#9: Helm Intro & GPU on Kubernetes for Machine Learning"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/12fqgtxd9H9fxsT5szOFkS87r8lm6XcZkF2Bvs46Uaec
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/pwuavFIsrA8
      slides: https://docs.google.com/presentation/d/1LAiZXFLG5GzgJABnfUy_tyhUtMfwa1JIiUI6lEwf378
      speakers:
      - rangga.adhitya.prawira
      title: Helm Intro, The Package Manager for Kubernetes
    - duration: 30m0s
      recording: https://youtu.be/o0O6ACyxkko
      slides: https://docs.google.com/presentation/d/1a0gMSbMh4q_qZDhdO7pW-z-JqrOP5KpIZayPRM6fxsg
      speakers:
      - eufrat.tsaqib
      title: GPU and Kubernetes for Machine Learning
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: female.daily.network
      role: Venue
  "20191003":
    title: "#10: Stateful Components & Service Mesh Observability"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/1n6_r_7iCxBrgxO00fdJbexkX8Zy1uvBlgM5M74DvSQQ
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/69voJLpcGLU
      slides: https://docs.google.com/presentation/d/1x1Qsfujw4WU7ucf-Lq-wdEcMcSg-u0E5QifJD5w2Flc
      speakers:
      - imrenagi
      title: Intro to StatefulSet with Case Study of Deploying Various Stateful Components
    - duration: 30m0s
      recording: https://youtu.be/vX5-VIVvlmE
      slides: https://www.slideshare.net/isnuryusuf/kubernetes-jakarta-meetup-010-service-mesh-observability-with-kiali
      speakers:
      - yusuf.hadiwinata
      title: Service Mesh Observability with Kiali
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: kalibrr
      role: Venue
  "20191129":
    title: "#11: Extending Kubernetes with Custom Resource & Optimizing Java Containers"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/11a4ENdfBMDGb-xnSMoLZeI-E3R-cEddTkyde7No_NLY
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/tnb4Uu7BW1g
      slides: https://speakerdeck.com/reyhansofian/extending-kubernetes-with-custom-resources
      speakers:
      - reyhan.sofian
      title: Extending Kubernetes with Custom Resources
    - duration: 30m0s
      slides: https://drive.google.com/file/d/1UvCYitOMxGA4DAm0YqsuB-4BoeT6jXCF/view
      speakers:
      - arga.dhahana
      title: Optimizing Java Containers on Kubernetes for Government Usecases
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: microsoft
      role: Venue
  "20191219":
    title: "#12: Kubernetes Autoscaling & Airy's Kubernetes Journey in AWS"
    presentations:
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/1Mwy6iZrgTp2irpg_n_AwbOS9C27UXagvL9KL5x1A19k
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/3j_IUiPflf4
      slides: https://docs.google.com/presentation/d/1p-PwgOk_DLZkTmGRTK37PLOut2rxWUXxnPOqPmKZ2t4
      speakers:
      - william.dembo
      title: "Intro to Kubernetes Autoscaling: HPA, VPA, CA, and beyond"
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=idUYQ7NRw4A
      slides: https://drive.google.com/open?id=1g6RkmYd4rC8iBt5gNFKCa5IkHQYoD6Jw
      speakers:
      - kurnianto.trilaksono
      title: Airy's Journey on Adopting Kubernetes in AWS and Intro to Telepresence
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: aws
      role: Venue
