meetupID: Jakarta-Kubernetes
meetupName: Jakarta Kubernetes
organizers:
- girikuncoro
- irvifa
- imrenagi
- iqbalfarabi
meetups:
  "20180110":
    title: "#1: Intro to Kubernetes and Knative"
    presentations:
    - duration: 9m0s
      slides: ""
      speakers:
      - imrenagi
      title: Welcome from the organizers
    - duration: 11m0s
      slides: https://docs.google.com/presentation/d/1VF_u0IYnvi0f-W2siKdFV8P1x6m6qzzblgYIAc5ZPq0
      speakers:
      - girikuncoro
      title: Kubernetes upstream community update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=DZQOgIWN1pE
      slides: https://bit.ly/knative
      speakers:
      - pahleviauliya
      title: Exploring KNative
    - duration: 30m0s
      recording: ""
      slides: https://speakerdeck.com/luxas/intro-to-the-cloud-native-world-of-kubernetes-helsinki-october-meetup
      speakers:
      - iqbalfarabi
      title: https://slides.com/qblfrb/kubernetesthe-ruby-way-71#
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: gojek
      role: Venue
