meetupID: Jakarta-Kubernetes
meetupName: Jakarta Kubernetes
organizers:
- eufrattsaqib
- girikuncoro
- irvifa
- imrenagi
- iqbalfarabi
meetups:
  "20190110":
    title: "#1: Intro to Kubernetes and Knative"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/01-community-slide.pdf
      speakers:
      - imrenagi
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=DZQOgIWN1pE
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/01-exploring-knative.pdf
      speakers:
      - pahleviauliya
      title: Exploring KNative
    - duration: 30m0s
      recording: ""
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/01-kubernetes-the-ruby-way.pdf
      speakers:
      - iqbalfarabi
      title: Kubernetes Fundamentals, The Beginning
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: gojek
      role: Venue
  "20190207":
    title: "#2: Kubernetes Architecture & Bukalapak Casestudy"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/02-community-slide.pdf
      speakers:
      - imrenagi
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=eGUc4OPNMyU
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/02-kubernetes-architecture-and-installation.pdf
      speakers:
      - girikuncoro
      title: Kubernetes Architecture and Installation
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=gY6qUGp60pc
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/02-kubernetes-at-bukalapak.pdf
      speakers:
      - christoper.hans
      title: Kubernetes at Bukalapak, An SRE Perspective
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: biznet.gio
      role: Venue
  "20190312":
    title: "#3: Istio Night"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/03-community-slide.pdf
      speakers:
      - iqbalfarabi
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=q-RWPjnJ2Y0&t=149
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/03-stop-reinventing-the-wheel-with-istio.pdf
      speakers:
      - mete.atamel
      title: Stop Reinventing The Wheel with Istio
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=q-RWPjnJ2Y0&t=2974
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/03-running-istio-in-traveloka-data-production.pdf
      speakers:
      - imrenagi
      title: Running Istio in TVLK Data Production
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: traveloka
      role: Venue
  "20190411":
    title: "#4: Kubernetes API Server and Service Discovery"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/04-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=IePXdP02eIo&t=5633
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/04-consul-and-kubernetes.pdf
      speakers:
      - lukluk.santoso
      title: Service Discovery with Consul on Kubernetes
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=IePXdP02eIo&t=3700
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/04-kubernetes-api-server.pdf
      speakers:
      - irvifa
      title: Understanding Kubernetes API Server
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: cbncloud
      role: Venue
    - company: hpe
      role: Venue
  "20190511":
    title: "#5: Kubernetes Networking, CKA, and How to Contribute"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/05-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/lJeKWFSy2nM
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/05-networking-model-and-services-in-kubernetes.pdf
      speakers:
      - arkan
      title: Networking Model and Services in Kubernetes
    - duration: 30m0s
      recording: https://youtu.be/AX-Rgs0SRrs
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/05-journey-and-tips-passing-cka-certification.pdf
      speakers:
      - husni.alhamdani
      title: Journey and Tips on Passing CKA Certification
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=Zi2CzdQjx2Y
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/05-how-to-contribute-to-kubernetes.pdf
      speakers:
      - irvifa
      - girikuncoro
      title: How to Become Kubernetes Contributor
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: deeptech
      role: Venue
  "20190620":
    title: "#6: Service Mesh in AWS and Kube Deployment"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/06-community-slide.pdf
      speakers:
      - girikuncoro
      - imrenagi
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/kBKuIN5kBYI
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/06-kubernetes-deployment-rolling-update-scaling.pdf
      speakers:
      - indrajatiwidyatmoko
      title: Kubernetes Deployment, Rolling-Update, and Scaling
    - duration: 30m0s
      recording: https://youtu.be/xSEQb1FK0EY
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/06-service-mesh-on-aws.pdf
      speakers:
      - donnie.prakoso
      title: Service Mesh with AWS
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: kitabisa
      role: Venue
  "20190711":
    title: "#7: Kubernetes Birthday Celebration"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/07-community-slide.pdf
      speakers:
      - girikuncoro
      - imrenagi
      - irvifa
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      speakers:
      - luthfi.rachman
      title: Security Practices in Kubernetes
    - duration: 30m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/07-kuryr-kubernetes-interconnecting-kubernetes-with-openstack.pdf
      speakers:
      - zufardhiyaulhaq
      title: "Kuryr Kubernetes: Interconnecting Kubernetes with Openstack"
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: google
      role: Venue
  "20190801":
    title: "#8: Kubernetes Monitoring and Stateful Basics"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/08-community-slide.pdf
      speakers:
      - girikuncoro
      - iqbalfarabi
      - irvifa
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=bYFwBqfGsx4
      slides: http://ela.st/aravind
      speakers:
      - aravind
      title: Docker and Kubernetes Monitoring with Elastic Stack
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=drBa7aBwKtA
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/08-basic-of-stateful-and-storage-in-kubernetes.pdf
      speakers:
      - kevin.tanzil
      title: Basic of Stateful and Storage in Kubernetes
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: linkaja
      role: Venue
    - company: elastic
      role: Venue
  "20190904":
    title: "#9: Helm Intro & GPU on Kubernetes for Machine Learning"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/09-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/pwuavFIsrA8
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/09-helm-intro-package-manager-for-kubernetes.pdf
      speakers:
      - rangga.adhitya.prawira
      title: Helm Intro, The Package Manager for Kubernetes
    - duration: 30m0s
      recording: https://youtu.be/o0O6ACyxkko
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/09-gpu-and-kubernetes-for-machine-learning.pdf
      speakers:
      - eufrat.tsaqib
      title: GPU and Kubernetes for Machine Learning
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: female.daily.network
      role: Venue
  "20191003":
    title: "#10: Stateful Components & Service Mesh Observability"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/10-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/69voJLpcGLU
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/10-kubernetes-statefulset.pdf
      speakers:
      - imrenagi
      title: Intro to StatefulSet with Case Study of Deploying Various Stateful Components
    - duration: 30m0s
      recording: https://youtu.be/vX5-VIVvlmE
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/10-service-mesh-observability-with-kiali.pdf
      speakers:
      - yusuf.hadiwinata
      title: Service Mesh Observability with Kiali
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: kalibrr
      role: Venue
  "20191129":
    title: "#11: Extending Kubernetes with Custom Resource & Optimizing Java Containers"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/11-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/tnb4Uu7BW1g
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/11-extending-kubernetes-using-custom-resource.pdf
      speakers:
      - reyhan.sofian
      title: Extending Kubernetes with Custom Resources
    - duration: 30m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/11-optimizing-java-containers-for-government-usecases.pdf
      speakers:
      - arga.dhahana
      title: Optimizing Java Containers on Kubernetes for Government Usecases
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: microsoft
      role: Venue
  "20191219":
    title: "#12: Kubernetes Autoscaling & Airy's Kubernetes Journey in AWS"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/12-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://youtu.be/3j_IUiPflf4
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/12-intro-to-kubernetes-autoscaling.pdf
      speakers:
      - william.dembo
      title: "Intro to Kubernetes Autoscaling: HPA, VPA, CA, and beyond"
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=idUYQ7NRw4A
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/12-airy-journey-on-adopting-kubernetes-in-aws-and-intro-to-telepresence.pdf
      speakers:
      - kurnianto.trilaksono
      title: Airy's Journey on Adopting Kubernetes in AWS and Intro to Telepresence
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: aws
      role: Venue
  "20200130":
    title: "#13: Intro to Kubernetes & Kubeflow"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/13-community-slide.pdf
      speakers:
      - eufrat.tsaqib
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: ""
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/13-intro-to-kubernetes.pdf
      speakers:
      - kevin.nadhif
      title: "Intro to Kubernetes"
    - duration: 30m0s
      recording: ""
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/13-a-scalable-training-approach-using-kubeflow.pdf
      speakers:
      - alvin.prayuda
      title: "A Scalable Training Approach using Kubeflow"
    - duration: 30m0s
      recording: ""
      slides: ""
      speakers: null
      title: Hallway track (networking)
    sponsors:
    - company: nodeflux
      role: Venue
  "20200425":
    title: "#14: Understanding Kubernetes Core Concepts & Intro to SONA-CNI"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/14-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: http://www.youtube.com/watch?v=8BUc6E6aM_E&t=19m3s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/14-understanding-kubernetes-core-concepts.pdf
      speakers:
      - iqbalsyamil
      title: Understanding Kubernetes Core Concepts
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=8BUc6E6aM_E&t=1h03m19s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/14-sona-cni-for-kubernetes.pdf
      speakers:
      - aris.risdianto
      title: Intro to SONA CNI for Kubernetes Networking
    sponsors: null
  "20200630":
    title: "#16: Understanding Kubernetes Core Concepts & Intro to SONA-CNI"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/16-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=EtMAyqhz3kI
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/16-kubernetes-swarm-interconnection.ppt
      speakers:
      - zainal.abidin
      title: Interconnection Kubernetes with Swarm
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=EtMAyqhz3kI
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/16-intro-cluster-api.pdf
      speakers:
      - srinivasa.vasu
      title: Introduction to Cluster API
    sponsors: null
  "20200814":
    title: "#18: Container Image Promotion Pipelines, Securing k8s with Kubernetes Goat"
    presentations:
    - duration: 11m0s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/18-community-slide.pdf
      speakers:
      - girikuncoro
      title: Welcome from the organizers and upstream update
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=pf5jOGWoWU0&t=8m11s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/18-container-pipeline.pdf
      speakers:
      - batel.zohar
      title: Best Practices In Implementing Container Image Promotion Pipeline
    - duration: 30m0s
      recording: https://www.youtube.com/watch?v=pf5jOGWoWU0&t=46m11s
      slides: https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/18-securing-k8s-with-kubernetes-goat.pdf
      speakers:
      - m.yuga.nugraha
      title: Securing k8s using Kubernetes Goat
    sponsors: null
